name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-analyze:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build and analyze on SonarQube
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }} # Put the name of your token here
        run: .\build-analyze.ps1
        shell: pwsh
